name: NPM Auto Deprecate

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  auto-deprecate:
    name: NPM Auto Deprecate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

      - name: Use Node.js
        uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # tag=v3
        with:
          node-version: 17
          registry-url: 'https://registry.npmjs.org/'

      - name: Install Node.js dependencies
        run: npm i
      - name: Deprecate versions
        run: npm deprecate @sern/cli@dev "This is a deprecated version of @sern/cli@dev. Please use the latest dev version."
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}